version: '3.8'

services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - 5000:5000
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./configuration/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
  #     - ./configuration/nginx/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
  #     - ./configuration/nginx/ssl/nginx.key:/etc/nginx/ssl/nginx.key
  #     - ./configuration/nginx/html:/usr/share/nginx/html
  #   depends_on:
  #     - api
  #   restart: always

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: plant172839
      MYSQL_USER: polipharm
      MYSQL_PASSWORD: plant172839
      TZ: "Asia/Bangkok" # ตั้งค่าโซนเวลาเป็น Asia/Bangkok
    ports:
      - 3306:3306
    volumes:
      - ./configuration/database:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: phpmyadmin
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: plant172839
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - db
  
  # api:
  #   image: api
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   env_file:
  #     - .env # ✅ โหลดค่าจาก .env
  #   restart: on-failure

volumes:
  db_data:
