INSERT INTO products (product_name) VALUES
('ALPRAZOLAM 0.25'),
('ALPRAZOLAM 0.5'),
('Amarax 2'),
('Amco'),
('Amlovasc 5'),
('Antafit'),
('Apurinol 300'),
('Ascot 300'),
('Ascot 81'),
('Asmaline'),
('Benclamin'),
('Berclomin'),
('Betapress 10 fc'),
('Bofen 200'),
('Bofen 400'),
('Bronclear'),
('Calcetate'),
('Calcetate-M'),
('Cenarine'),
('Cenoxcin'),
('Ceremin'),
('Ciprox 250'),
('Cisapie 10 mg'),
('Clalergy'),
('Cravixin 500'),
('Domperdone'),
('Donecept 10'),
('Estab 250 mg'),
('Favogas'),
('Fluna 5 mg'),
('Forexin'),
('Forexin 500'),
('Furide'),
('Furide 500'),
('Gabanil 300'),
('Gabanil 400'),
('Gabanil 600'),
('Gabenine'),
('Gandin-ds'),
('Glazer'),
('Gliclabit'),
('Gliparil 2'),
('Gliparil 3'),
('Goutic'),
('Herpenon'),
('Hyospan'),
('Hypofrine'),
('Kelep 500'),
('Ketonazole'),
('Levente 500'),
('Leviq'),
('Levita 500'),
('Lofibrate 160'),
('Memantia 10'),
('Memantia 20'),
('Midil 10 mg'),
('Midil 5 mg'),
('Migrano'),
('Minibit'),
('Minoride'),
('Mucolo'),
('Musclofen'),
('Neupentin 300'),
('Neupentin 400'),
('Neupentin 600'),
('Neurogine 1 mg'),
('Nidol (EXP)'),
('Nidol (TH)'),
('Norflocin'),
('Norflocin 100'),
('Norflocin 200'),
('Norflocin 400'),
('Norgeb'),
('Nystin'),
('Ossium'),
('Pantol'),
('Paracetamol'),
('Peteyu'),
('Polibroxol'),
('Policifloxin 250'),
('Policifloxin 500'),
('Policoxia'),
('Policycline'),
('Poliformin'),
('Poliformin 850'),
('Poligot cf'),
('Poli-relaxane'),
('Poliroxin'),
('Politifen'),
('Poli-uretic'),
('Polizine'),
('Polizine 25'),
('Potrim'),
('Prasikon'),
('Presco'),
('PROSTASIN 2'),
('Prostasin 4'),
('Prostat 5'),
('Puride'),
('Puride 300'),
('Pyrecol'),
('Pyroid'),
('Rena'),
('Roxica'),
('Salbutac'),
('Sigas'),
('Taroxin 200'),
('Tenpress 100'),
('Tenpress 50'),
('Ticolid'),
('Travan 0.5'),
('Travan 1.0'),
('Triamzide'),
('Tripsyline 10'),
('Tripsyline 25'),
('Tymet 200'),
('Ulcimet 200'),
('Ulcimet 400'),
('Vermixide'),
('Lithium'),
('POLICOXIA 60'),
('Policoxia 90'),
('TRAVAN 2.0'),
('Herpenon 800'),
('Crestatin 20 tablet'),
('Clotri V.T.'),
('KELEP 250'),
('Roxaban 20'),
('Paindol capsule'),
('Polizep 5 cap'),
('Policycline 100 cap'),
('Pobalin 25 cap'),
('Clozepam 1.0'),
('Pobalin 75 cap'),
('Poliflunarin capsule'),
('MINO 50 capsule'),
('CRESTATIN 10 TABLET'),
('Norfa 400'),
('CLOZEPAM 2.0'),
('Prostat 1'),
('CLOZEPAM 0.5'),
('OMEC CAP'),
('OMEC (N) CAP'),
('OPRAMED CAP'),
('ULPRACID CAP'),
('ULPRAZOLE CAP'),
('Itrafungal capsule'),
('Osteotin 500'),
('ALPRAZOLAM 1.0'),
('Sanosec capsule'),
('Pregabalin 75 Eurodrug'),
('PREGABALIN 25 EURODRUG'),
('Actisac capsule'),
('POBALIN 50 CAP'),
('POBALIN 150 CAP'),
('DOMAR capsule'),
('MIGESIC capsule'),
('CRAVIXIN 750'),
('POLILERGY TABLET'),
('AMLOVASC 10'),
('BLANK FOR COATING FORMULA 4'),
('GLIPTIN 100 TABLET'),
('Gliptin 50 TABLET'),
('Clarius'),
('VIBRAREX'),
('Q-fluna'),
('HOFXIB 90');