// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Printer

#include "../ui.h"

void ui_DetailsPage_screen_init(void)
{
    ui_DetailsPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DetailsPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DetailsPage, lv_color_hex(0x53E1FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DetailsPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_DetailsPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_DetailsPage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_DetailsPage);
    lv_img_set_src(ui_Image7, &ui_img_polipharm2_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 267
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 267
    lv_obj_set_x(ui_Image7, 0);
    lv_obj_set_y(ui_Image7, -115);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 200);

    ui_Label22 = lv_label_create(ui_DetailsPage);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 0);
    lv_obj_set_y(ui_Label22, 222);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Create by engineering department");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SerialNumber = lv_label_create(ui_DetailsPage);
    lv_obj_set_width(ui_SerialNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SerialNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SerialNumber, 0);
    lv_obj_set_y(ui_SerialNumber, 191);
    lv_obj_set_align(ui_SerialNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SerialNumber, "Serial number: ESP32-XXXXXXXX");
    lv_obj_set_style_text_color(ui_SerialNumber, lv_color_hex(0xF4660A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SerialNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SerialNumber, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MachineName = lv_label_create(ui_DetailsPage);
    lv_obj_set_width(ui_MachineName, 600);
    lv_obj_set_height(ui_MachineName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MachineName, 0);
    lv_obj_set_y(ui_MachineName, 55);
    lv_obj_set_align(ui_MachineName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MachineName, "XXXXXXXX");
    lv_obj_set_style_text_color(ui_MachineName, lv_color_hex(0x695C62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MachineName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MachineName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MachineName, &ui_font_Chakra100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpdateDetails = lv_btn_create(ui_DetailsPage);
    lv_obj_set_width(ui_UpdateDetails, 145);
    lv_obj_set_height(ui_UpdateDetails, 55);
    lv_obj_set_x(ui_UpdateDetails, -90);
    lv_obj_set_y(ui_UpdateDetails, 140);
    lv_obj_set_align(ui_UpdateDetails, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpdateDetails, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UpdateDetails, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UpdateDetails, lv_color_hex(0x405BE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UpdateDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_UpdateDetails);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "อัพเดท");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home = lv_btn_create(ui_DetailsPage);
    lv_obj_set_width(ui_Home, 145);
    lv_obj_set_height(ui_Home, 55);
    lv_obj_set_x(ui_Home, 90);
    lv_obj_set_y(ui_Home, 140);
    lv_obj_set_align(ui_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 2);
    lv_obj_set_y(ui_Label24, 0);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "หน้าหลัก");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

}
