// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Printer

#include "../ui.h"

void ui_MainPage_screen_init(void)
{
    ui_MainPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header = lv_obj_create(ui_MainPage);
    lv_obj_set_width(ui_Header, 793);
    lv_obj_set_height(ui_Header, 97);
    lv_obj_set_x(ui_Header, 0);
    lv_obj_set_y(ui_Header, -191);
    lv_obj_set_align(ui_Header, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Header, lv_color_hex(0x170DF3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logout = lv_btn_create(ui_Header);
    lv_obj_set_width(ui_Logout, 91);
    lv_obj_set_height(ui_Logout, 65);
    lv_obj_set_x(ui_Logout, 132);
    lv_obj_set_y(ui_Logout, 0);
    lv_obj_set_align(ui_Logout, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logout, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Logout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Logout);
    lv_img_set_src(ui_Image5, &ui_img_logout5_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image5, 7);
    lv_obj_set_y(ui_Image5, 2);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 115);

    ui_Date = lv_label_create(ui_Header);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, 307);
    lv_obj_set_y(ui_Date, -20);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "dd/mm/yyyy");
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_Header);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 323);
    lv_obj_set_y(ui_Time, 16);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "hh:mm:ss");
    lv_obj_set_style_text_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Header);
    lv_obj_set_width(ui_Panel4, 120);
    lv_obj_set_height(ui_Panel4, 65);
    lv_obj_set_x(ui_Panel4, -235);
    lv_obj_set_y(ui_Panel4, 0);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x0290F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x0290F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -17);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "OPERATOR 1");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmployeeID1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_EmployeeID1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EmployeeID1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EmployeeID1, 0);
    lv_obj_set_y(ui_EmployeeID1, 10);
    lv_obj_set_align(ui_EmployeeID1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmployeeID1, "2077");
    lv_obj_set_style_text_color(ui_EmployeeID1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EmployeeID1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EmployeeID1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EmployeeID1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Header);
    lv_img_set_src(ui_Image1, &ui_img_polipharm2_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 327
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 291
    lv_obj_set_x(ui_Image1, -348);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 70);

    ui_Panel5 = lv_obj_create(ui_Header);
    lv_obj_set_width(ui_Panel5, 120);
    lv_obj_set_height(ui_Panel5, 65);
    lv_obj_set_x(ui_Panel5, -106);
    lv_obj_set_y(ui_Panel5, 0);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x0290F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x0290F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -17);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "OPERATOR 2");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmployeeID2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_EmployeeID2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EmployeeID2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EmployeeID2, 0);
    lv_obj_set_y(ui_EmployeeID2, 10);
    lv_obj_set_align(ui_EmployeeID2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmployeeID2, "2077");
    lv_obj_set_style_text_color(ui_EmployeeID2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EmployeeID2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EmployeeID2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EmployeeID2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mode = lv_btn_create(ui_Header);
    lv_obj_set_width(ui_Mode, 115);
    lv_obj_set_height(ui_Mode, 65);
    lv_obj_set_x(ui_Mode, 19);
    lv_obj_set_y(ui_Mode, 0);
    lv_obj_set_align(ui_Mode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Mode, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Mode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Mode);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -17);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "MODE");

    ui_ModeLabel = lv_label_create(ui_Mode);
    lv_obj_set_width(ui_ModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ModeLabel, 0);
    lv_obj_set_y(ui_ModeLabel, 10);
    lv_obj_set_align(ui_ModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeLabel, "กรัม");
    lv_obj_set_style_text_font(ui_ModeLabel, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GramPanel = lv_obj_create(ui_MainPage);
    lv_obj_set_width(ui_GramPanel, 783);
    lv_obj_set_height(ui_GramPanel, 368);
    lv_obj_set_x(ui_GramPanel, 0);
    lv_obj_set_y(ui_GramPanel, 48);
    lv_obj_set_align(ui_GramPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GramPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_GramPanel, lv_color_hex(0xECE8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GramPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GramPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GramPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GramPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GramPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GramPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GramPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_GramPanel);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 166);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Create by engineering department");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_GramPanel);
    lv_obj_set_width(ui_Panel3, 760);
    lv_obj_set_height(ui_Panel3, 196);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -80);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x9E9696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel3, lv_color_hex(0xB1A5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel6, 521);
    lv_obj_set_height(ui_Panel6, 166);
    lv_obj_set_x(ui_Panel6, 106);
    lv_obj_set_y(ui_Panel6, 1);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel6, lv_color_hex(0xF59307), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel6, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentWeight = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_CurrentWeight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentWeight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentWeight, -18);
    lv_obj_set_y(ui_CurrentWeight, -14);
    lv_obj_set_align(ui_CurrentWeight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentWeight, "000.00");
    lv_obj_set_style_text_color(ui_CurrentWeight, lv_color_hex(0x4D4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentWeight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrentWeight, &ui_font_Chakra130, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GramUnit = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_GramUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GramUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GramUnit, 229);
    lv_obj_set_y(ui_GramUnit, 9);
    lv_obj_set_align(ui_GramUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GramUnit, "g.");
    lv_obj_set_style_text_color(ui_GramUnit, lv_color_hex(0x177330), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GramUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GramUnit, &ui_font_Chakra50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -221);
    lv_obj_set_y(ui_Label16, 62);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "OK:");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x177330), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_sukhumvit30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OkGramCount = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_OkGramCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OkGramCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OkGramCount, -142);
    lv_obj_set_y(ui_OkGramCount, 62);
    lv_obj_set_align(ui_OkGramCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OkGramCount, "00000");
    lv_obj_set_style_text_color(ui_OkGramCount, lv_color_hex(0x177330), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OkGramCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OkGramCount, &ui_font_sukhumvit30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -37);
    lv_obj_set_y(ui_Label17, 62);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "NG:");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x822336), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_sukhumvit30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NgGramCount = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_NgGramCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NgGramCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NgGramCount, 40);
    lv_obj_set_y(ui_NgGramCount, 62);
    lv_obj_set_align(ui_NgGramCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NgGramCount, "00000");
    lv_obj_set_style_text_color(ui_NgGramCount, lv_color_hex(0x822336), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NgGramCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NgGramCount, &ui_font_sukhumvit30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetGramCount = lv_btn_create(ui_Panel6);
    lv_obj_set_width(ui_ResetGramCount, 94);
    lv_obj_set_height(ui_ResetGramCount, 35);
    lv_obj_set_x(ui_ResetGramCount, 156);
    lv_obj_set_y(ui_ResetGramCount, 58);
    lv_obj_set_align(ui_ResetGramCount, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetGramCount, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ResetGramCount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResetGramCount, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_ResetGramCount);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Reset");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_Image4, &ui_img_scale_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Image4, -263);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 100);

    ui_SetMinWeight = lv_obj_create(ui_GramPanel);
    lv_obj_set_width(ui_SetMinWeight, 233);
    lv_obj_set_height(ui_SetMinWeight, 88);
    lv_obj_set_x(ui_SetMinWeight, -230);
    lv_obj_set_y(ui_SetMinWeight, 100);
    lv_obj_set_align(ui_SetMinWeight, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SetMinWeight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetMinWeight, lv_color_hex(0xA3A8A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetMinWeight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinWeight = lv_label_create(ui_SetMinWeight);
    lv_obj_set_width(ui_MinWeight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinWeight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MinWeight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinWeight, "000.00");
    lv_obj_set_style_text_color(ui_MinWeight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinWeight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinWeight, &ui_font_Chakra50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_GramPanel);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -230);
    lv_obj_set_y(ui_Label10, 40);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Min. (g.)");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetMaxWeight = lv_obj_create(ui_GramPanel);
    lv_obj_set_width(ui_SetMaxWeight, 233);
    lv_obj_set_height(ui_SetMaxWeight, 88);
    lv_obj_set_x(ui_SetMaxWeight, 230);
    lv_obj_set_y(ui_SetMaxWeight, 100);
    lv_obj_set_align(ui_SetMaxWeight, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SetMaxWeight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetMaxWeight, lv_color_hex(0xA3A8A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetMaxWeight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxWeight = lv_label_create(ui_SetMaxWeight);
    lv_obj_set_width(ui_MaxWeight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxWeight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MaxWeight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxWeight, "000.00");
    lv_obj_set_style_text_color(ui_MaxWeight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MaxWeight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MaxWeight, &ui_font_Chakra50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_GramPanel);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 230);
    lv_obj_set_y(ui_Label7, 40);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Max. (g.)");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LedGramResult = lv_obj_create(ui_GramPanel);
    lv_obj_set_width(ui_LedGramResult, 156);
    lv_obj_set_height(ui_LedGramResult, 67);
    lv_obj_set_x(ui_LedGramResult, 3);
    lv_obj_set_y(ui_LedGramResult, 100);
    lv_obj_set_align(ui_LedGramResult, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LedGramResult, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LedGramResult, lv_color_hex(0x0C5107), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LedGramResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LedGramResult, lv_color_hex(0xE4DADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LedGramResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LedGramResult, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LedGramResult, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GramResult = lv_label_create(ui_LedGramResult);
    lv_obj_set_width(ui_GramResult, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GramResult, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GramResult, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GramResult, "ผ่าน/ไม่ผ่าน");
    lv_obj_set_style_text_color(ui_GramResult, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GramResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GramResult, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrintLogo = lv_switch_create(ui_GramPanel);
    lv_obj_set_width(ui_PrintLogo, 110);
    lv_obj_set_height(ui_PrintLogo, 30);
    lv_obj_set_x(ui_PrintLogo, -281);
    lv_obj_set_y(ui_PrintLogo, -99);
    lv_obj_set_align(ui_PrintLogo, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_PrintLogo, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PrintLogo, lv_color_hex(0x04F16D), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PrintLogo, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_radius(ui_PrintLogo, 5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PcsPanel = lv_obj_create(ui_MainPage);
    lv_obj_set_width(ui_PcsPanel, 783);
    lv_obj_set_height(ui_PcsPanel, 368);
    lv_obj_set_x(ui_PcsPanel, 0);
    lv_obj_set_y(ui_PcsPanel, 48);
    lv_obj_set_align(ui_PcsPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PcsPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PcsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PcsPanel, lv_color_hex(0xECE8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PcsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PcsPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PcsPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PcsPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PcsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PcsPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PcsPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_PcsPanel);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 166);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Create by engineering department");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_PcsPanel);
    lv_obj_set_width(ui_Panel2, 451);
    lv_obj_set_height(ui_Panel2, 184);
    lv_obj_set_x(ui_Panel2, 148);
    lv_obj_set_y(ui_Panel2, -80);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel2, lv_color_hex(0xF59307), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentPcs = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_CurrentPcs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentPcs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentPcs, -49);
    lv_obj_set_y(ui_CurrentPcs, -17);
    lv_obj_set_align(ui_CurrentPcs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentPcs, "000");
    lv_obj_set_style_text_color(ui_CurrentPcs, lv_color_hex(0x4D4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentPcs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrentPcs, &ui_font_Chakra130, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PcsUnit = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_PcsUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PcsUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PcsUnit, 141);
    lv_obj_set_y(ui_PcsUnit, 7);
    lv_obj_set_align(ui_PcsUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PcsUnit, "PCS");
    lv_obj_set_style_text_color(ui_PcsUnit, lv_color_hex(0x177330), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PcsUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PcsUnit, &ui_font_Chakra50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OkPcsCount = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_OkPcsCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OkPcsCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OkPcsCount, -107);
    lv_obj_set_y(ui_OkPcsCount, 70);
    lv_obj_set_align(ui_OkPcsCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OkPcsCount, "00000");
    lv_obj_set_style_text_color(ui_OkPcsCount, lv_color_hex(0x177330), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OkPcsCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OkPcsCount, &ui_font_sukhumvit30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -185);
    lv_obj_set_y(ui_Label20, 70);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "OK:");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x177330), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_sukhumvit30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -20);
    lv_obj_set_y(ui_Label21, 70);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "NG:");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x822336), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_sukhumvit30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NgPcsCount = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_NgPcsCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NgPcsCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NgPcsCount, 57);
    lv_obj_set_y(ui_NgPcsCount, 70);
    lv_obj_set_align(ui_NgPcsCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NgPcsCount, "00000");
    lv_obj_set_style_text_color(ui_NgPcsCount, lv_color_hex(0x822336), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NgPcsCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NgPcsCount, &ui_font_sukhumvit30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetPcsCount = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_ResetPcsCount, 94);
    lv_obj_set_height(ui_ResetPcsCount, 35);
    lv_obj_set_x(ui_ResetPcsCount, 160);
    lv_obj_set_y(ui_ResetPcsCount, 66);
    lv_obj_set_align(ui_ResetPcsCount, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetPcsCount, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ResetPcsCount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResetPcsCount, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_ResetPcsCount);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Reset");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LedPcsResult = lv_obj_create(ui_PcsPanel);
    lv_obj_set_width(ui_LedPcsResult, 156);
    lv_obj_set_height(ui_LedPcsResult, 75);
    lv_obj_set_x(ui_LedPcsResult, 249);
    lv_obj_set_y(ui_LedPcsResult, 95);
    lv_obj_set_align(ui_LedPcsResult, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LedPcsResult, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LedPcsResult, lv_color_hex(0x0C5107), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LedPcsResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LedPcsResult, lv_color_hex(0xE4DADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LedPcsResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LedPcsResult, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LedPcsResult, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PcsResult = lv_label_create(ui_LedPcsResult);
    lv_obj_set_width(ui_PcsResult, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PcsResult, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PcsResult, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PcsResult, "ผ่าน/ไม่ผ่าน");
    lv_obj_set_style_text_color(ui_PcsResult, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PcsResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PcsResult, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetPcs = lv_obj_create(ui_PcsPanel);
    lv_obj_set_width(ui_SetPcs, 156);
    lv_obj_set_height(ui_SetPcs, 75);
    lv_obj_set_x(ui_SetPcs, 50);
    lv_obj_set_y(ui_SetPcs, 95);
    lv_obj_set_align(ui_SetPcs, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SetPcs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetPcs, lv_color_hex(0xA3A8A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetPcs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PcsMonitor = lv_label_create(ui_SetPcs);
    lv_obj_set_width(ui_PcsMonitor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PcsMonitor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PcsMonitor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PcsMonitor, "000");
    lv_obj_set_style_text_color(ui_PcsMonitor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PcsMonitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PcsMonitor, &ui_font_Chakra50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_PcsPanel);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 51);
    lv_obj_set_y(ui_Label15, 45);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "SET PCS");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_PcsPanel);
    lv_img_set_src(ui_Image3, &ui_img_scale_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Image3, -225);
    lv_obj_set_y(ui_Image3, -5);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 150);

    ui_Label1 = lv_label_create(ui_PcsPanel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 248);
    lv_obj_set_y(ui_Label1, 45);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "RESULT");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrintPcs = lv_switch_create(ui_PcsPanel);
    lv_obj_set_width(ui_PrintPcs, 94);
    lv_obj_set_height(ui_PrintPcs, 35);
    lv_obj_set_x(ui_PrintPcs, -155);
    lv_obj_set_y(ui_PrintPcs, -113);
    lv_obj_set_align(ui_PrintPcs, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_PrintPcs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrintPcs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrintPcs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_PrintPcs, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_PrintPcs, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PrintPcs, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_radius(ui_PrintPcs, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrintPcs, lv_color_hex(0xFF0022), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrintPcs, 150, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrintPcs, 10, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_PrintPcs, lv_color_hex(0x01B500), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PrintPcs, 150, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label14 = lv_label_create(ui_PcsPanel);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -150);
    lv_obj_set_y(ui_Label14, -135);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "PRINT");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x474545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PNKEYBOARD = lv_obj_create(ui_MainPage);
    lv_obj_set_width(ui_PNKEYBOARD, 789);
    lv_obj_set_height(ui_PNKEYBOARD, 422);
    lv_obj_set_x(ui_PNKEYBOARD, 0);
    lv_obj_set_y(ui_PNKEYBOARD, 28);
    lv_obj_set_align(ui_PNKEYBOARD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PNKEYBOARD, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PNKEYBOARD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PNKEYBOARD, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PNKEYBOARD, lv_color_hex(0xAFB4B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PNKEYBOARD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_PNKEYBOARD);
    lv_keyboard_set_mode(ui_Keyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard, 768);
    lv_obj_set_height(ui_Keyboard, 317);
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 47);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0xAFB4B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0x0DB1A2), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Keyboard, &lv_font_montserrat_40, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_input = lv_textarea_create(ui_PNKEYBOARD);
    lv_obj_set_width(ui_input, 744);
    lv_obj_set_height(ui_input, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_input, 0);
    lv_obj_set_y(ui_input, -154);
    lv_obj_set_align(ui_input, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_input, 20);
    lv_textarea_set_placeholder_text(ui_input, "SET...");
    lv_textarea_set_one_line(ui_input, true);
    lv_obj_set_style_text_color(ui_input, lv_color_hex(0x605858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_input, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_input, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_input, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_input, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_keyboard_set_textarea(ui_Keyboard, ui_input);

}
