// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Printer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_LoadingPage
void ui_LoadingPage_screen_init(void);
lv_obj_t * ui_LoadingPage;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label13;
lv_obj_t * ui_LoadingLabel;


// SCREEN: ui_DetailsPage
void ui_DetailsPage_screen_init(void);
lv_obj_t * ui_DetailsPage;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label22;
lv_obj_t * ui_SerialNumber;
lv_obj_t * ui_MachineName;
lv_obj_t * ui_UpdateDetails;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Home;
lv_obj_t * ui_Label24;


// SCREEN: ui_LoginPage
void ui_LoginPage_screen_init(void);
lv_obj_t * ui_LoginPage;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label12;
lv_obj_t * ui_PnEmployeeID1;
lv_obj_t * ui_EmployeeIDValue1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_PnEmployeeID2;
lv_obj_t * ui_EmployeeIDValue2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Login;
lv_obj_t * ui_Label11;
lv_obj_t * ui_PnLoginKeyboard;
lv_obj_t * ui_LoginKeyboard;
lv_obj_t * ui_LoginInput;


// SCREEN: ui_MainPage
void ui_MainPage_screen_init(void);
lv_obj_t * ui_MainPage;
lv_obj_t * ui_Header;
lv_obj_t * ui_Logout;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Date;
lv_obj_t * ui_Time;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label3;
lv_obj_t * ui_EmployeeID1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_EmployeeID2;
lv_obj_t * ui_Mode;
lv_obj_t * ui_Label8;
lv_obj_t * ui_ModeLabel;
lv_obj_t * ui_GramPanel;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_CurrentWeight;
lv_obj_t * ui_GramUnit;
lv_obj_t * ui_Label16;
lv_obj_t * ui_OkGramCount;
lv_obj_t * ui_Label17;
lv_obj_t * ui_NgGramCount;
lv_obj_t * ui_ResetGramCount;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Image4;
lv_obj_t * ui_SetMinWeight;
lv_obj_t * ui_MinWeight;
lv_obj_t * ui_Label10;
lv_obj_t * ui_SetMaxWeight;
lv_obj_t * ui_MaxWeight;
lv_obj_t * ui_Label7;
lv_obj_t * ui_LedGramResult;
lv_obj_t * ui_GramResult;
lv_obj_t * ui_PrintLogo;
lv_obj_t * ui_PcsPanel;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_CurrentPcs;
lv_obj_t * ui_PcsUnit;
lv_obj_t * ui_OkPcsCount;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_NgPcsCount;
lv_obj_t * ui_ResetPcsCount;
lv_obj_t * ui_Label19;
lv_obj_t * ui_LedPcsResult;
lv_obj_t * ui_PcsResult;
lv_obj_t * ui_SetPcs;
lv_obj_t * ui_PcsMonitor;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label1;
lv_obj_t * ui_PrintPcs;
lv_obj_t * ui_Label14;
lv_obj_t * ui_PNKEYBOARD;
lv_obj_t * ui_Keyboard;
lv_obj_t * ui_input;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_logout[1] = {&ui_img_logout5_png};
const lv_img_dsc_t * ui_imgset_polipharm[1] = {&ui_img_polipharm2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_LoadingPage_screen_init();
    ui_DetailsPage_screen_init();
    ui_LoginPage_screen_init();
    ui_MainPage_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_LoadingPage);
}
